# Generated by Django 5.1.7 on 2025-05-02 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentdeposithistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='agentdeposithistory',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='agentdeposithistory',
            name='transaction_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agentdeposithistory',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
