# Generated by Django 5.1.7 on 2025-05-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_alter_agentdeposithistory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentdeposithistory',
            old_name='commission',
            new_name='commission_earned',
        ),
        migrations.AddField(
            model_name='agentdeposithistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
    ]
