# Generated by Django 5.1.7 on 2025-05-03 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0003_rename_commission_agentdeposithistory_commission_earned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='agent',
        ),
        migrations.RenameField(
            model_name='agentdeposithistory',
            old_name='user_email',
            new_name='sender_email',
        ),
        migrations.AddField(
            model_name='agentdeposithistory',
            name='receiver_email',
            field=models.EmailField(blank=True, default='unknown@example.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='agentdeposithistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='agentdeposithistory',
            index=models.Index(fields=['agent', 'timestamp'], name='deposit_age_agent_i_795216_idx'),
        ),
        migrations.AddIndex(
            model_name='agentdeposithistory',
            index=models.Index(fields=['status'], name='deposit_age_status_79baf0_idx'),
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
