# Generated by Django 5.1.7 on 2025-03-15 11:03

import agents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_code',
            field=models.CharField(default=agents.models.generate_unique_agent_code, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
