# Generated by Django 5.1.7 on 2025-05-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserWithdrawsUsingAgent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentbalanceupdate',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
