# Generated by Django 5.1.7 on 2025-05-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserWithdrawsUsingAgent', '0002_alter_agentbalanceupdate_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentbalanceupdate',
            old_name='transaction_fee',
            new_name='commission_earned',
        ),
        migrations.AddField(
            model_name='agentbalanceupdate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentbalanceupdate',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
