# Generated by Django 5.1.7 on 2025-05-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserWithdrawsUsingAgent', '0004_agentwithdrawalhistory_delete_agentbalanceupdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentwithdrawalhistory',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='agentwithdrawalhistory',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
