# Generated by Django 5.1.7 on 2025-05-03 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentTransfers', '0002_rename_transaction_fee_transfer_commission_earned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revenue',
        ),
        migrations.AddField(
            model_name='transfer',
            name='receiver_email',
            field=models.EmailField(blank=True, default='unknown@example.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender_email',
            field=models.EmailField(blank=True, default='unknown@example.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['sender', 'time_stamp'], name='agentTransf_sender__8852d3_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['receiver', 'time_stamp'], name='agentTransf_receive_ee086a_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status'], name='agentTransf_status_73f3bb_idx'),
        ),
    ]
