# Generated by Django 5.1.6 on 2025-03-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secmomo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='agent_code',
            field=models.CharField(default='AGENT0001', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='agents',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='agents',
            name='number',
            field=models.CharField(default='0000000000', max_length=20, unique=True),
        ),
    ]
