# Generated by Django 5.1.6 on 2025-04-19 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secmomo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='agent_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agents',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agents',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='agents',
            name='min_required_balance',
            field=models.DecimalField(decimal_places=2, default=200000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='agents',
            name='mobile_money_user_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agents',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=10),
        ),
    ]
