# Generated by Django 5.1.6 on 2025-03-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secmomo', '0002_agents_agent_code_agents_balance_agents_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='agent_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
