# Generated by Django 5.1.6 on 2025-04-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secmomo', '0003_remove_agents_approved_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentapplication',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
