# Generated by Django 5.1.6 on 2025-03-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secmomo', '0003_alter_agents_agent_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='agent_code',
            field=models.CharField(default='AGENT0001', max_length=50, unique=True),
        ),
    ]
