# Generated by Django 5.1.6 on 2025-03-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secmomo', '0004_alter_agents_agent_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='agent_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='agents',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
