# Generated by Django 5.1.6 on 2025-04-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secmomo', '0004_alter_agentapplication_current_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentapplication',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='agentapplication',
            name='proof_of_address',
        ),
    ]
