# Generated by Django 5.1.6 on 2025-04-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secmomo', '0005_remove_agentapplication_id_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
