# Generated by Django 5.1.6 on 2025-04-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secmomo', '0006_alter_agents_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
