# Generated by Django 5.1.6 on 2025-04-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secmomo', '0009_agentapplication_username_alter_agents_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentapplication',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
