# Generated by Django 5.1.7 on 2025-05-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secmomo', '0010_alter_agentapplication_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=10),
        ),
    ]
