# Generated by Django 5.1.6 on 2025-05-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secmomo', '0012_rename_agent_code_agents_agentcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
